### ISSUE TITLE
Add `GetFuturePositioning` to `Game.Object.IObjectToFollow`

### ISSUE THREAD

**Issue by Asu4ni** [Asu4ni/CSkyL#1]
For Asu4ni/CitiesSkylines-FPSCamera#42 to work, we need a new method to get the future/target position(ing) for `IObjectToFollow`.

**Comment by kianzarrin** [comment]
One problem with IObjectToFollow is that it is destroyed and recreated every frame and therefore is unable to record history or handle mutli-threading. that is why I have so far done this in the FollowCam.
but I can fix the issue with IObjectToFollow. we need to use ref to get Vehicle/CitizenInstance. that way there is no need to recreate it every frame.

**Comment by Asu4ni** [comment]
done via #3
